#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GroupSaver.Resource", IsApplication=true)]

namespace GroupSaver
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GroupSaver.DataBase.Resource.String.ApplicationName = global::GroupSaver.Resource.String.ApplicationName;
			global::GroupSaver.DataBase.Resource.String.Hello = global::GroupSaver.Resource.String.Hello;
			global::GroupSaver.VkAPI.Resource.String.ApplicationName = global::GroupSaver.Resource.String.ApplicationName;
			global::GroupSaver.VkAPI.Resource.String.Hello = global::GroupSaver.Resource.String.Hello;
			global::PCLCrypto.Resource.String.ApplicationName = global::GroupSaver.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::GroupSaver.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int buttonFavourite = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int buttonLoadMoreGroups = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int buttonLoadMorePosts = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int buttonSearchGroup = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int buttonSubscribe = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int editTextGroupName = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int listViewPosts = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int textViewGroupName = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int textViewUserInfo = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PostsLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Favourite = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
